### ISSUE TITLE
cannot paste in console ?

### ISSUE THREAD

**Issue by kevincobain2000** [rails/web-console#36]
Hi there. Just a quick question. As we are not able to (CMD+v) in the web console, is this feature intentionally disabled or do have plans in near future?

Thanks

**Comment by chengguangnan** [comment]
Not sure why is this closed. I still can't paste. 

- web-console 2.0.0 
- OSX 
- Chrome and Safari

**Comment by parterburn** [comment]
@chengguangnan same here. The PR #106 addresses it.

If you want a temporary fix you can add the following style to your own CSS file:
```
#console #clipboard {
  visibility: visible !important;
  height: 0px;
  border: 0px;
  padding: 0px;
  margin: 0px;
  width: 0px;
}
```

**Comment by rodrigobdz** [comment]
@ryandao Could you reopen this issue? It's still not working. 
### Details
- OS: OSX
- web-console: Version 3.7.0
- Browser: Google Chrome Version 70.0.3538.77 (Official Build) (64-bit)

**Comment by rodrigobdz** [comment]
ping @ryandao. Please reopen

**Comment by gsamokovarov** [comment]
I'll reopen it, but can you folks give me some more context about your environment? Browser, keyboard layout (US, European), OS, etc?

**Comment by benjaminb10** [comment]
Mac OS X 10.14
AZERTY keyboard
Chrome 71

**Comment by swordfish444** [comment]
@gsamokovarov 	What's the latest on this issue? Was this fixed at one point? Did it regress? 

Multi-line commands (including copy/paste) are not working.

```
Rails 5.1.6
Google Chrome (Version 71.0.3578.98 (Official Build) (64-bit))
2017 Macbook Pro (US keyboard)
```

**Comment by rempargo** [comment]
I need to click multiple times **⌘V**, but it is very inconsistent, sometimes 5 times, sometimes 3, and sometimes only 1 time, but in rare cases also 9 times.

    Rails 5.2.2
    Google Chrome Version 72.0.3626.119 (Official Build) (64-bit)
    MacBook Pro (15-inch, 2018)
    Keyboard: English International

**Comment by estani** [comment]
Got fixed for 4.0 (Rails 6), it wasn't ported back to 3.7 (Rails 5) though, so if you are still on rails 5.0 you'll have to manually add the change from #285 to the already downloaded gem.
I've tested and it works. In my case (rbenv) the file was here to be found: `~/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/web-console-3.7.0/lib/web_console/templates/console.js.erb`

**Comment by estani** [comment]
Just a heads up, this is in master, but still not released as of 4.0.1. In case someone is still wondering after 6 months. The patch should be something like:
```patch
--- a/web-console-4.0.1/lib/web_console/templates/console.js.erb     2020-05-04 11:26:58.000000000 +0200
+++ b/web-console-4.0.1/lib/web_console/templates/console.js.erb 2020-05-04 11:26:45.000000000 +0200
@@ -760,7 +760,7 @@
         _this.addToInput(_this.clipboard.value);
         _this.clipboard.value = "";
         _this.clipboard.blur();
+      }, 100);
-      }, 10);
     }
   }
```

**Comment by gsamokovarov** [comment]
You have a point, I have been holding on `4.0.2` for too long. It's released now with #285 applied.
